[project]
name = "paper-translate-bot"
version = "0.1.0"
description = "Slack bot translating a paper"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "deepl>=1.18.0",
    "python-dotenv>=1.0.1",
    "requests>=2.32.3",
    "slack-bolt>=1.20.1",
    "slack-sdk>=3.31.0",
]
